/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package rs.exproit.load_profile_generator.protocol;

@SuppressWarnings("all")
/** The RPC API of our smart meter. */
@org.apache.avro.specific.AvroGenerated
public interface LoadProfileRPC {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"LoadProfileRPC\",\"namespace\":\"rs.exproit.load_profile_generator.protocol\",\"doc\":\"The RPC API of our smart meter.\",\"types\":[{\"type\":\"record\",\"name\":\"LPCreationRequest\",\"fields\":[{\"name\":\"loadCondition\",\"type\":[\"null\",\"string\"],\"doc\":\"The identifier for the referenced data (may be null if the controller doesn't collect meta-data).\",\"default\":null}]},{\"type\":\"error\",\"name\":\"ServiceError\",\"fields\":[{\"name\":\"code\",\"type\":\"int\",\"doc\":\"The application error code.\"},{\"name\":\"message\",\"type\":\"string\",\"doc\":\"The application error message.\"}]}],\"messages\":{\"lpCreate\":{\"request\":[{\"name\":\"request\",\"type\":\"LPCreationRequest\"}],\"response\":\"string\",\"errors\":[\"ServiceError\"]}}}");
  /**
   */
  java.lang.CharSequence lpCreate(rs.exproit.load_profile_generator.protocol.LPCreationRequest request) throws org.apache.avro.AvroRemoteException, rs.exproit.load_profile_generator.protocol.ServiceError;

  @SuppressWarnings("all")
  /** The RPC API of our smart meter. */
  public interface Callback extends LoadProfileRPC {
    public static final org.apache.avro.Protocol PROTOCOL = rs.exproit.load_profile_generator.protocol.LoadProfileRPC.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void lpCreate(rs.exproit.load_profile_generator.protocol.LPCreationRequest request, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
  }
}