/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package rs.exproit.load_profile_generator.domain;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Category {
  INDUSTRIAL, RESIDENTIAL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Category\",\"namespace\":\"rs.exproit.load_profile_generator.domain\",\"symbols\":[\"INDUSTRIAL\",\"RESIDENTIAL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
